reposcan: fix support with branches with /
Branch like next/5.25-release breaks python:

```
File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in
run_until_complete
return future.result()
  File "./bin/reposcan", line 35, in main_thread
  merge.metadata.flush_kit(out_tree)
  File "/repo/funtoo/merge/metadata.py", line 867, in flush_kit
  with open(outpath, "w") as f:
  FileNotFoundError: [Errno 2] No such file or directory:
  '/reposcan/repo_tmp/tmp/kit_cache/kde-kit-next/5.25-release'
```

In this case, I replace slash with - on path definition.