Continued refactor. Here's what to work on next:
Get merge-kits working again. Right now, running 'merge-kits prod'
produces a traceback:

  File "/home/drobbins/development/funtoo-metatools/funtoo/merge/metadata.py", line 600, in gen_cache
    eclass_hashes = merge.model.eclass_hashes.hashes.copy()
  AttributeError: 'EClassHashCollector' object has no attribute 'hashes'

This is because I need to complete the refactor of eclass hash
collecting and integration with gen_cache(). That's what I need
to work on next.